extends SceneTree
var game: Node
func frames(count: int):
	for i in range(count):
		await physics_frame
		game.hud.queue_redraw()
func _initialize(): call_deferred('run')
func run():
	game = load('res://main.tscn').instantiate()
	root.add_child(game)
	await frames(100)
	await game.screenshot('skills-island')
	game.player.position = Vector3(-7,.1,25)
	game.player.reset_physics_interpolation()
	game.set_process(false)
	game.camera.position = Vector3(0,6,31)
	game.camera.look_at(Vector3(-7,1.2,22))
	await frames(10)
	game.player.skills.use_skill(3)
	await frames(10)
	await game.screenshot('skills-fish')
	await frames(60)
	game.player.skills.use_skill(4)
	await frames(10)
	await game.screenshot('skills-ice')
	await frames(16)
	await game.screenshot('skills-ice-expanded')
	await frames(145)
	game.player.skills.use_skill(5)
	await frames(16)
	await game.screenshot('skills-fear')
	await frames(130)
	game.player.position = Vector3(-3,.1,25)
	game.player.reset_physics_interpolation()
	game.player.skills.use_skill(2)
	await frames(8)
	await game.screenshot('skills-dive')
	game.start_race()
	game.set_process(true)
	await frames(80)
	await game.screenshot('skills-race-hud')
	print('SKILLS PREVIEW: PASS')
	quit()
