extends SceneTree

func _initialize() -> void:
	var script = load('res://scripts/race_rules.gd')
	assert(script != null, 'Race rules must exist')
	var race = script.new()
	race.start()
	assert(race.phase == 'countdown')
	race.advance(2.9)
	assert(race.phase == 'countdown')
	race.advance(0.2)
	assert(race.phase == 'racing')
	assert(race.finish(7) == 1)
	assert(race.finish(7) == 1, 'Duplicate finish must not add a place')
	assert(race.order.size() == 1)
	for i in range(23):
		race.finish(100 + i)
	assert(race.phase == 'ended', 'Qualification capacity ends race')
	assert(race.finish(999) == 0, 'Late racers cannot qualify')
	race.start()
	assert(race.order.is_empty())
	race.advance(3.0)
	race.advance(150.0)
	assert(race.phase == 'ended', 'Time limit ends race')
	assert(race.finish(0) == 0)
	race.start()
	race.advance(3)
	race.advance(42)
	assert(race.time_left() == 108 and race.first_finish == -1)
	assert(race.finish(3) == 1)
	assert(race.time_left() == 30 and race.places_left() == 23)
	race.advance(20)
	assert(race.finish(4) == 2)
	assert(race.time_left() == 10, 'Later finishes never extend deadline')
	race.advance(9.99)
	assert(race.finish(5) == 3, 'Finish just before deadline qualifies')
	race.advance(.02)
	assert(race.phase == 'ended' and race.end_reason == 'finish_window')
	assert(race.elapsed == 72 and race.finish(6) == 0)
	race.start()
	assert(race.first_finish == -1 and race.end_reason == '' and race.time_left() == 150)
	race.advance(3)
	race.advance(145)
	race.finish(8)
	assert(race.time_left() == 5, 'Global time limit still applies to a late first finish')
	race.advance(5)
	assert(race.end_reason == 'time_limit')
	race.start(true)
	race.advance(500)
	assert(race.phase == 'racing' and race.first_finish == -1, 'Practice stays unlimited')
	assert(race.finish(0) == 1 and race.end_reason == 'practice')
	print('PASS: countdown, duplicate finish, 24-place cutoff, timeout, restart')
	quit()
